# Exercise configuration file

agent_base: "duckietown_baseline" #
ws_dir: "solution" # directory that contains the code
agent_run_cmd: "run_and_start.sh" # the script in "launchers" to run the agent with
challenge: aido-LF-sim-validation
ros: True
